IMAGE_NAME = ubuntu
IMAGE_VERSION = xenial
IMAGE_VERSION_ALIASES = 16.04
IMAGE_TITLE = Ubuntu Xenial
IMAGE_DESCRIPTION = Ubuntu Xenial (16.04 LTS)
IMAGE_SOURCE_URL = https://github.com/scaleway/image-ubuntu
IMAGE_VENDOR_URL = http://www.ubuntu.com
IMAGE_BOOTSCRIPT_arm64 = longterm 4.9 latest
IMAGE_BOOTSCRIPT = longterm 4.4 latest
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
