IMAGE_NAME = ubuntu
IMAGE_VERSION = bionic
IMAGE_VERSION_ALIASES = 18.04
IMAGE_TITLE = Ubuntu Bionic Beaver
IMAGE_DESCRIPTION = Ubuntu Bionic Beaver (18.04 LTS)
IMAGE_SOURCE_URL = https://github.com/scaleway/image-ubuntu
IMAGE_VENDOR_URL = http://www.ubuntu.com
IMAGE_BOOTSCRIPT_arm = longterm 4.9 latest
IMAGE_BOOTSCRIPT = longterm 4.14 latest
IMAGE_BASE_FLAVORS = common docker-based systemd feature-motd
